// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_NEW_ANDROID_API_KEY_HERE',
    appId: '1:476519585832:android:997cb3f707a0eea1993d1d',
    messagingSenderId: '476519585832',
    projectId: 'workify-cb9a0',
    storageBucket: 'workify-cb9a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_NEW_IOS_API_KEY_HERE',
    appId: '1:476519585832:ios:e84fffccc8132fcc993d1d',
    messagingSenderId: '476519585832',
    projectId: 'workify-cb9a0',
    storageBucket: 'workify-cb9a0.firebasestorage.app',
    iosBundleId: 'com.example.jobhubv20',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_NEW_WEB_API_KEY_HERE',
    appId: '1:476519585832:web:cca4e464c1428aaa993d1d',
    messagingSenderId: '476519585832',
    projectId: 'workify-cb9a0',
    authDomain: 'workify-cb9a0.firebaseapp.com',
    storageBucket: 'workify-cb9a0.firebasestorage.app',
    measurementId: 'G-8ZQ8LV440L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_NEW_MACOS_API_KEY_HERE',
    appId: '1:476519585832:ios:f775e6c3adbf6658993d1d',
    messagingSenderId: '476519585832',
    projectId: 'workify-cb9a0',
    storageBucket: 'workify-cb9a0.firebasestorage.app',
    iosBundleId: 'com.dbestech.jobhubv20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_NEW_WINDOWS_API_KEY_HERE',
    appId: '1:476519585832:web:db4f6613401637b9993d1d',
    messagingSenderId: '476519585832',
    projectId: 'workify-cb9a0',
    authDomain: 'workify-cb9a0.firebaseapp.com',
    storageBucket: 'workify-cb9a0.firebasestorage.app',
    measurementId: 'G-7TZKSJVHP5',
  );
}
